version: "3.7"
services:
  app:
    init: true
    build: .
    command: sleep infinity
    volumes:
      - ../:/app
    env_file:
      - app.env
    ports: 
      - 3000:3000
      - 4000:4000
  mongo:
    image: mongo
